server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/orderdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ORDER_SERVICE
  jackson.serialization.indent_output: true

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.health.circuitbreakers.enabled: true

info:
  name: ${spring.application.name}
  description: spring boot microservices demo
  environment: ${spring.profiles.active}
  version: 0.0.1

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        failore-rate-threshhole: 50
        minimum-number-of-calls: 5
        aotumatic-transection-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException